events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # Proxy /api/add to the add-service
        location /api/add {
            rewrite ^/api/add(.*) /$1 break;
            proxy_pass http://add-service;
        }

        location /api/sub {
            proxy_pass http://sub-service/;
        }

        location /api/mul {
            proxy_pass http://mul-service/;
        }

        location /api/div {
            proxy_pass http://div-service/;
        }

        location /api/mem {
            rewrite ^/api/mem(.*) /$1 break;
            proxy_pass http://mem-service;
        }

        location /api/sqrt {
            proxy_pass http://sqrt-service/;
        }
    }
}
